name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.9', '3.8']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qy libunwind-dev pkg-config nodejs npm
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox tox-gh-actions
    - name: Run tox
      run: tox . -vvv

  lint_and_docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qy clang-format nodejs npm libunwind-dev pkg-config
        npm install -g prettier
    - name: Install Python dependencies
      run: |
        python3 -m pip install -r requirements-extra.txt
    - name: Install Package
      run: |
        python3 -m pip install -e .
    - name: Lint sources
      run: |
        make lint
    - name: Build docs
      run: |
        make docs

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qy libunwind-dev pkg-config nodejs npm valgrind
    - name: Install Python dependencies and package
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements-test.txt
        python3 -m pip install -e .
    - name: Run Valgrind
      run: make valgrind
    - name: Run Helgrind
      run: make helgrind

